######################################################################
#
# File name : CAMERE_TOP_wave.do
# Created on: Fri Jan 04 15:14:51 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
