######################################################################
#
# File name : CAMERE_TOP_compile.do
# Created on: Fri Jan 04 15:14:45 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Mathlogic\\modelsim\\win32pe\\vlib work
D:\\Mathlogic\\modelsim\\win32pe\\vlib msim

D:\\Mathlogic\\modelsim\\win32pe\\vlib msim/xil_defaultlib
D:\\Mathlogic\\modelsim\\win32pe\\vlib msim/xpm
D:\\Mathlogic\\modelsim\\win32pe\\vlib msim/blk_mem_gen_v8_3_3

D:\\Mathlogic\\modelsim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
D:\\Mathlogic\\modelsim\\win32pe\\vmap xpm msim/xpm
D:\\Mathlogic\\modelsim\\win32pe\\vmap blk_mem_gen_v8_3_3 msim/blk_mem_gen_v8_3_3

D:\\Mathlogic\\modelsim\\win32pe\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../project_CAMERA_TOP.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \

D:\\Mathlogic\\modelsim\\win32pe\\vcom -64 -93 -work xpm  \
"D:/Mathlogic/vivado/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \

D:\\Mathlogic\\modelsim\\win32pe\\vlog -64 -incr -work blk_mem_gen_v8_3_3  "+incdir+../../../project_CAMERA_TOP.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../project_CAMERA_TOP.ip_user_files/ipstatic/blk_mem_gen_v8_3_3/simulation/blk_mem_gen_v8_3.v" \

D:\\Mathlogic\\modelsim\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../project_CAMERA_TOP.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../project_CAMERA_TOP.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/RGB565_Capture.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/divider.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/display7.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/SYNC.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/CONTROL.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/RGB565_Config.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/SCCB_Timing_Control.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV_clk_wiz.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/display_data.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/SDRAM.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/VGA.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/OV2640_Driver.v" \
"../../../project_CAMERA_TOP.srcs/sources_1/new/CAMERE_TOP.v" \

# compile glbl module
D:\\Mathlogic\\modelsim\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

