# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Project_Auway/project_CAMERA_TOP/project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV.xci
# IP: The module: 'CLK_DIV' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Project_Auway/project_CAMERA_TOP/project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_DIV'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Project_Auway/project_CAMERA_TOP/project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_DIV'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Project_Auway/project_CAMERA_TOP/project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_DIV'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: F:/Project_Auway/project_CAMERA_TOP/project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV.xci
# IP: The module: 'CLK_DIV' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Project_Auway/project_CAMERA_TOP/project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_DIV'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Project_Auway/project_CAMERA_TOP/project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_DIV'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Project_Auway/project_CAMERA_TOP/project_CAMERA_TOP.srcs/sources_1/ip/CLK_DIV/CLK_DIV_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_DIV'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
